#!/bin/bash

mvn dependency:copy-dependencies
LIB_FILES=`find target/dependency -follow -iname "*.jar"`
LIB_FILES=`echo $LIB_FILES | sed -e 's/ /:/g'`
java -cp $LIB_FILES:target/classes -graal -G:+TraceTruffleCompilationDetails -G:LogFile=/tmp/graal.log -G:+PrintCompilation -G:+TraceTruffleCompilationHistogram -G:TruffleCompilationThreshold=1 -Xmx8G -Xms8G -Xmn1G org.neo4j.shell.StartClient $@
